### PR TITLE
Filter parameters

### PR DESCRIPTION
**Pull request by anagpuyol**
Added UI to filter parameters. Only selected parameters will be included in the JSON file.

Step 1:
image
If Yes is clicked, the only elements that get exported are those that are visible in the view. Otherwise, the command is run as before. Also, included a toggle for the type parameters. 

Step 2:
image

### CODE REVIEW

**Comment by jeremytammik** [comment]
hi ana, thank you! this looks absolutely great and i would love to pull it! however, you have based your code on version 2015.0.0.27, and i recently updated to 2015.0.0.29. would it be possible for you to check out the most up-to-date version and submit a new pull request based on that? thank you very much! cheers, jeremy.

**Comment by anagpuyol** [comment]
@jeremytammik I have your commits in my branch. Could you give me some pointers on how to fix these conflicts?
revit va3c

**Comment by jeremytammik** [comment]
hi @anagpuyol, the copyright year update is completely trivial: just increment the copyright year. the other highlighted issue was just a single click for me... i don''t know how hard it would be for you. it was to add the new DynVa3c "va3s for dynamo" that someone submitted. i would have thought that the simplest way to handle this would be for you to clone the current version in a separate folder and then compare that with your current version. then you can transfer the diffs that you require to the newer version as well. that is the way i normally handle these kind of things. i hope this helps. thank you! cheers, jeremy.

**Comment by jeremytammik** [comment]
ana submitted an updated pull request #7 and we merged that instead. this one has the great UI description, though, so we need to keep this one alive as well as documentation.

**Pull request closed without merging**
